// src/lib/components/NavMenu.svelte
<script lang="ts">
  import { page } from "$app/state";
  import { clickOutside } from "$lib/actions/clickOutside.svelte";

  type Props = {
    open: boolean;
    onClose: () => void;
  };

  let { open, onClose }: Props = $props();
</script>

<div
  class:open
  class="isolate z-50 group fixed top-0 left-0 h-dvh w-full pointer-events-none"
>
  <aside
    class="fixed bottom-0 z-50 block w-screen translate-y-full px-responsive transition-transform pointer-events-auto group-[.open]:translate-y-0"
  >
    <div
      class="w-full h-full bg-background-100 border border-border px-8 pt-8 pb-32 rounded-t-sm"
      use:clickOutside
      onclickoutside={onClose}
    >
      <ul class="flex flex-col gap-3 text-3xl font-semibold text-text-dark/80">
        {@render entry("/", "Hjem", onClose)}
        {@render entry("/menu", "Menu", onClose)}
        {@render entry("/om-os", "Om os", onClose)}
        {@render entry("/kontakt", "Kontakt", onClose)}
      </ul>
    </div>
  </aside>

  <!-- BACKGROUND -->
  <div
    class="fixed top-0 left-0 h-full w-full bg-[black]/50 opacity-0 transition-opacity group-[.open]:opacity-100 group-[.open]:pointer-events-auto"
  ></div>
</div>

{#snippet entry(pathname: string, title: string, onClose: () => void)}
  {@const active = page.url.pathname === pathname}
  <li
    class:active
    class="[.active]:font-bold [.active]:underline [.active]:text-text-dark"
  >
    <a onclick={onClose} href={pathname}>{title}</a>
  </li>
{/snippet}

// frontend/src/lib/components/navbar/nav-menu.tsx
import { Link, useRouterState } from "@tanstack/react-router";
import { forwardRef, type HTMLAttributes } from "react";
import type { NavEntry } from "./entry";
import { cn } from "../../class";

type Props = {
	entries: NavEntry[]
	open: boolean;
	onSelect: () => void;
}

const NavMenu = ({ entries, open, onSelect }: Props) => {
	return (
		<>
			<div className={cn("z-15 fixed top-0 left-0 h-svh w-screen bg-[black] opacity-0 pointer-events-none transition-opacity duration-1000", open && "opacity-50")} />
			<aside className={cn("z-15 fixed top-0 left-0 h-svh w-screen -translate-y-full transition-transform p-2", open && "translate-y-0")}>
				<div className="h-full flex justify-center items-center bg-background-100 border border-border rounded-b-sm">
					<ul className={cn("flex flex-col gap-3 items-center opacity-0 transition-opacity delay-100 duration-400", open && "opacity-100")}>
						{entries.map(entry => <Entry key={entry.title} entry={entry} onClick={onSelect} />)}
					</ul>
				</div>
			</aside>
		</>
	)
}

type EntryProps = HTMLAttributes<HTMLLIElement> & {
	entry: NavEntry
}

const Entry = forwardRef<HTMLLIElement, EntryProps>(({ entry, title, ...rest }, ref) => {
	const { location } = useRouterState()
	const active = entry.to && location.pathname.includes(entry.to)

	return (
		<li ref={ref} {...rest}>
			<Link
				title={entry.title}
				to={entry.to}
				className={cn("text-3xl font-bold-no-shift", active && "font-bold underline")}
			>
				{entry.title}
			</Link>
		</li>
	)
})

export default NavMenu
