// frontend/src/features/employees/components/employee-list.tsx
import { type Employee } from "../employee"
import { LuArchive, LuArchiveRestore, LuCircleUserRound, LuTrash } from "react-icons/lu"
import { Link } from "@tanstack/react-router"
import { cn } from "../../../lib/class"
import ActionButton from "../../../lib/components/action-button"
import type { ComponentType } from "react"

type BaseProps = {
	employees: Employee[]
	onDelete: (id: number) => void;

	Fallback: ComponentType
}

type Props = BaseProps &
	({
		variant: "employed"
		onArchive: (id: number) => void;
		onRestore?: never;
	} | {
		variant: "non-employed"
		onRestore: (id: number) => void;
		onArchive?: never;
	})

const EmployeeList = ({ employees, variant, Fallback, onDelete, onArchive, onRestore }: Props) => {
	if (employees.length === 0) return <Fallback />

	return (
		<ul className="flex flex-col gap-2">
			{employees.map((employee) => (
				<Entry
					key={employee.id}
					variant={variant}
					employee={employee}
					onArchive={() => onArchive?.(employee.id)}
					onDelete={() => onDelete?.(employee.id)}
					onRestore={() => onRestore?.(employee.id)}
				/>
			))}
		</ul>
	)
}

type EntryProps = {
	employee: Employee
	variant: "employed" | "non-employed"

	onDelete: (id: number) => void;
	onArchive?: (id: number) => void;
	onRestore?: (id: number) => void;
}

const Entry = ({ employee, variant, onArchive, onRestore, onDelete }: EntryProps) => (
	<li className="group w-full flex bg-background-100 border border-border/75 rounded-sm items-center hover:bg-background-200" key={employee.id}>
		<Link
			to="/admin/employees/$employeeId"
			params={{ employeeId: employee.id.toString() }}
			className="flex items-center flex-1 gap-8 p-4"
		>
			<EmployeeImage src={employee.imageSrc} alt={employee.name} />

			<div className="flex flex-col flex-1">
				<h2 className="font-serif font-bold text-xl group-hover:underline">{employee.name}</h2>
				<p className={cn("text-text-dark/75", !employee.role && "italic")}>
					{employee.role || "Ingen rolle bestemt..."}
				</p>
			</div>
		</Link>

		<div className="flex p-4">
			{variant === "employed" ? (
				<ActionButton
					title="Arkivér (Hall of Fame)"
					onClick={() => onArchive?.(employee.id)}
					confirmation={`Arkivér ${employee.name}?\n\nOBS: Den ansætte sættes i Hall of Fame.`}
				>
					{employee.archived ? <LuArchiveRestore /> : <LuArchive />}
				</ActionButton>
			) : (
				<ActionButton
					title="Genansæt"
					onClick={() => onRestore?.(employee.id)}
					confirmation={`Genansæt ${employee.name}?`}
				>
					{employee.archived ? <LuArchiveRestore /> : <LuArchive />}
				</ActionButton>
			)}

			<ActionButton
				title="Slet"
				onClick={() => onDelete(employee.id)}
				confirmation={`Slet ${employee.name}?\n\nOBS: Handlingen kan ikke fortrydes.`}
			>
				<LuTrash />
			</ActionButton>
		</div>
	</li>
)

type EmployeeImageProps = {
	src: string | undefined
	alt: string
}

const EmployeeImage = ({ src, alt }: EmployeeImageProps) => (
	src ? (
		<img src={src} alt={alt} className="h-20 aspect-square object-cover rounded-full" />
	) : (
		<LuCircleUserRound className="text-8xl text-border" />
	)
)


export default EmployeeList

// frontend/src/lib/features/employees/components/employee-list/EmployeeList.svelte
<script lang="ts">
  import ActionButton from "$lib/components/ActionButton.svelte";
  import { fade } from "svelte/transition";
  import type { Employee } from "../../employee";
  import {
    archiveEmployee,
    deleteEmployee,
    moveEmployee,
    restoreEmployee,
  } from "../../employees.remote";

  type Props = {
    employees: Employee[];
    emptyText: string;
    variant: "employed" | "archived";
  };

  let { employees, emptyText, variant }: Props = $props();
</script>

{#snippet entry(employee: Employee, idx: number)}
  <li
    transition:fade={{ duration: 100 }}
    class="group flex w-full items-center rounded-lg border border-border/75 bg-surface-100 hover:bg-surface-200"
  >
    <a
      href="/admin/employees/{employee.id}"
      class="flex flex-1 items-center gap-8 p-4"
    >
      {#if employee.src}
        <img
          src={employee.src}
          alt={employee.name}
          class="aspect-square h-18 rounded-full object-cover"
        />
      {:else}
        <span class="icon-[lucide--circle-user-round] text-7xl"></span>
      {/if}

      <div class="flex flex-1 flex-col">
        <h2 class="font-serif text-xl font-bold group-hover:underline">
          {employee.name}
        </h2>
        <p class={["text-text-dark-muted", !employee.role && "italic"]}>
          {employee.role || "Ingen rolle..."}
        </p>
      </div>
    </a>

    <div class="flex items-center p-4">
      {#if variant === "employed"}
        <ActionButton
          title="Arkivér {employee.name}"
          prompt="Er du sikker på, at du vil arkivere {employee.name}?"
          onclick={() => archiveEmployee(employee.id)}
          class="px-3!"
        >
          <span class="icon-[lucide--archive]"></span>
        </ActionButton>
      {:else}
        <ActionButton
          title="Genansæt {employee.name}"
          prompt="Er du sikker på, at du vil genansætte {employee.name}?"
          onclick={() => restoreEmployee(employee.id)}
          class="px-3!"
        >
          <span class="icon-[lucide--archive-restore]"></span>
        </ActionButton>
      {/if}

      <ActionButton
        title="Slet {employee.name}"
        prompt="Er du sikker på, at du vil slette {employee.name}?"
        onclick={() => deleteEmployee(employee.id)}
        class="px-3!"
      >
        <span class="icon-[lucide--trash]"></span>
      </ActionButton>

      {#if variant === "employed"}
        <div class="flex flex-col">
          <ActionButton
            onclick={() => moveEmployee({ id: employee.id, direction: -1 })}
            title="Flyt op"
            disabled={idx === 0}
            class="px-3!"
          >
            <span class="icon-[lucide--chevron-up]"></span>
          </ActionButton>

          <ActionButton
            onclick={() => moveEmployee({ id: employee.id, direction: 1 })}
            title="Flyt ned"
            disabled={idx === employees.length - 1}
            class="px-3!"
          >
            <span class="icon-[lucide--chevron-down]"></span>
          </ActionButton>
        </div>
      {/if}
    </div>
  </li>
{/snippet}

{#if employees.length === 0}
  <span class="text-text-dark-muted italic">{emptyText}</span>
{:else}
  <ul class="flex flex-col gap-2">
    {#each employees as employee, i (employee.id)}
      {@render entry(employee, i)}
    {/each}
  </ul>
{/if}
