// frontend/src/routes/admin/dashboard.tsx
import { createFileRoute } from '@tanstack/react-router'
import { useQueryClient, useSuspenseQuery } from '@tanstack/react-query'

import { useAuth } from '../../lib/context/auth'
import { deleteUser, updateUserApproval } from '../../features/auth/user'
import { archiveEmployee, deleteEmployee, restoreEmployee } from '../../features/employees/employee'

import { employeesQueryOpts } from '../../features/employees/query'
import { usersQueryOptions } from '../../features/auth/query'

import { LuPlus } from 'react-icons/lu'
import { LinkButton } from '../../lib/components/button'
import EmployeeList from '../../features/employees/components/employee-list'
import UserList from '../../features/auth/components/user-list'

export const Route = createFileRoute('/admin/dashboard')({
	component: RouteComponent,
	loader: async ({ context: { queryClient } }) => {
		queryClient.ensureQueryData(usersQueryOptions())
		queryClient.ensureQueryData(employeesQueryOpts())
	}
})

function RouteComponent() {
	const { data: employees } = useSuspenseQuery(employeesQueryOpts())
	const { data: users } = useSuspenseQuery(usersQueryOptions())
	const { user: currentUser } = useAuth()

	const queryClient = useQueryClient()

	const approvedUsers = users.filter(u => u.approved)
	const nonApprovedUsers = users.filter(u => !u.approved)

	const activeEmployees = employees.filter(e => !e.archived)
	const archivedEmployees = employees.filter(e => e.archived)

	const handleApproveUser = async (id: number) => {
		await updateUserApproval(id, "approve")
		await queryClient.invalidateQueries({ queryKey: ["users"] })
	}

	const handleRejectUser = async (id: number) => {
		await updateUserApproval(id, "reject")
		await queryClient.invalidateQueries({ queryKey: ["users"] })
	}

	const handleDeleteUser = async (id: number) => {
		await deleteUser(id)
		await queryClient.invalidateQueries({ queryKey: ["users"] })
	}

	const handleDeleteEmployee = async (id: number) => {
		await deleteEmployee(id)
		await queryClient.invalidateQueries({ queryKey: ["employees"] })
	}

	const handleArhiveEmployee = async (id: number) => {
		await archiveEmployee(id)
		queryClient.invalidateQueries({ queryKey: ["employees"] })
	}

	const handleRestoreEmployee = async (id: number) => {
		await restoreEmployee(id)
		queryClient.invalidateQueries({ queryKey: ["employees"] })
	}

	return (
		<main className="py-32 px-8 flex flex-col gap-32">
			<section className="mx-responsive w-full">
				<div className="@container">
					<div className="grid grid-cols-1 @4xl:grid-cols-2 gap-32">
						<section className="">
							<div className="mb-8 flex justify-between">
								<h1 className="font-bold font-serif text-4xl mb">Ansatte</h1>
								<LinkButton to="/admin/employees/create" className="px-3 py-1">
									<LuPlus />Tilføj
								</LinkButton>
							</div>

							<EmployeeList
								employees={activeEmployees}
								variant="employed"
								onDelete={handleDeleteEmployee}
								onArchive={handleArhiveEmployee}
								Fallback={() => <span>Ingen ansatte...</span>}
							/>
						</section>

						<section>
							<h1 className="font-bold font-serif text-4xl mb-8">Hall of Fame</h1>
							<EmployeeList
								variant="non-employed"
								employees={archivedEmployees}
								Fallback={() => <span>Ingen tidligere ansatte...</span>}
								onDelete={handleDeleteEmployee}
								onRestore={handleRestoreEmployee}
							/>
						</section>
					</div>
				</div>
			</section>

			<section className="mx-responsive w-full">
				<div className="@container">
					<div className="mb-8">
						<h1 className="font-bold font-serif text-4xl mb-4">Administratorer</h1>
						<p className="text-text-dark/75">
							Overblik af administratorer af hjemmesiden. Administratorer er i stand
							til at tilføje, redigére og slette ansatte, samt godkende, afvise og
							slette administratorer.
						</p>
					</div>

					<div className="grid grid-cols-1 gap-16 @4xl:gap-32 @4xl:grid-cols-2">
						<div>
							<h1 className="font-serif font-bold mb-4">Nuværende</h1>
							<UserList
								variant="approved"
								users={approvedUsers}
								currentUser={currentUser}
								onDelete={handleDeleteUser}
								Fallback={() => <span>Ingen brugere...</span>}
							/>
						</div>

						<div>
							<h1 className="font-serif font-bold mb-4">Anmodninger</h1>
							<UserList
								variant="pending"
								users={nonApprovedUsers}
								currentUser={currentUser}
								onApprove={handleApproveUser}
								onReject={handleRejectUser}
								Fallback={() => <span>Ingen anmodninger...</span>}
							/>
						</div>
					</div>
				</div >
			</section>
		</main>
	)
}

// frontend/src/routes/admin/dashboard/+page.svelte
<script lang="ts">
  import Button from "$lib/components/Button.svelte";
  import Input from "$lib/components/Input.svelte";
  import EmployeeList from "$lib/features/employees/components/employee-list/EmployeeList.svelte";
  import UserList from "$lib/features/users/components/UserList.svelte";

  let { data } = $props();

  let approvedUsers = $derived(data.users.filter((u) => u.approved));
  let nonApprovedUsers = $derived(data.users.filter((u) => !u.approved));
  let activeEmployees = $derived(data.employees.filter((e) => !e.archived));
  let archivedEmployees = $derived(data.employees.filter((e) => e.archived));
</script>

<main class="flex flex-col gap-32 px-8 py-32">
  <section class="mx-responsive w-full">
    <div class="@container">
      <div class="grid grid-cols-1 gap-32 @4xl:grid-cols-2">
        <section class="">
          <div class="mb-8 flex justify-between">
            <h1 class="mb font-serif text-4xl font-bold">Ansatte</h1>
            <Button href="/admin/employees/create" class="px-3 py-1">
              <span class="icon-[lucide--plus]"></span>
              Tilføj
            </Button>
          </div>

          <EmployeeList
            deleteAction="?/deleteEmployee"
            archiveAction="?/archiveEmployee"
            moveUpAction="?/moveEmployeeUp"
            moveDownAction="?/moveEmployeeDown"
            employees={activeEmployees}
            variant="employed"
            emptyText="Ingen ansatte..."
          />
        </section>

        <section>
          <h1 class="mb-8 font-serif text-4xl font-bold">Hall of Fame</h1>
          <EmployeeList
            variant="archived"
            deleteAction="?/deleteEmployee"
            restoreAction="?/restoreEmployee"
            employees={archivedEmployees}
            emptyText="Intet at se her..."
          />
        </section>
      </div>
    </div>
  </section>

  <section class="mx-responsive w-full">
    <h1 class="mb-8 font-serif text-4xl font-bold">FAQ</h1>
    <form action="?/createQuestion" class="mb-8 flex gap-2">
      <Input name="title" placeholder="Spørgsmål" class="w-full" />
      <Input name="description" placeholder="Svar" class="w-full" />
      <Button><span class="icon-[lucide--plus]"></span>Tilføj</Button>
    </form>

    <ul class="flex flex-col gap-8 divide-y divide-border/50">
      {#each data.questions as question, i}
        <li>
          <form
            action="?/editQuestion&id={question.id}"
            class="flex flex-col gap-2"
          >
            <div class="flex gap-2 font-serif">
              <span>#{i + 1}</span>
              <input
                placeholder="Spørgsmål"
                maxlength="50"
                name="title"
                value={question.title}
                class="w-full font-bold"
              />
            </div>
            <textarea
              placeholder="Svar"
              name="description"
              value={question.description}
            ></textarea>
          </form>
        </li>
      {/each}
    </ul>
  </section>

  <section class="mx-responsive w-full">
    <div class="@container">
      <div class="mb-8">
        <h1 class="mb-4 font-serif text-4xl font-bold">Administratorer</h1>
        <p class="text-text-dark-muted">
          Overblik af administratorer af hjemmesiden. Administratorer er i stand
          til at tilføje, redigére og slette ansatte, samt godkende, afvise og
          slette administratorer.
        </p>
      </div>

      <div class="grid grid-cols-1 gap-16 @4xl:grid-cols-2 @4xl:gap-32">
        <div>
          <h1 class="mb-4 font-serif font-bold">Nuværende</h1>
          <UserList
            variant="approved"
            users={approvedUsers}
            currentUser={data.currentUser}
            deleteAction="?/deleteUser"
            emptyText="Ingen godkendte brugere..."
          />
        </div>

        <div>
          <h1 class="mb-4 font-serif font-bold">Anmodninger</h1>
          <UserList
            variant="pending"
            users={nonApprovedUsers}
            currentUser={data.currentUser}
            approveAction="?/approveUser"
            rejectAction="?/deleteUser"
            emptyText="Ingen brugeranmodninger..."
          />
        </div>
      </div>
    </div>
  </section>
</main>
