// frontend/src/lib/components/Button.svelte
<script lang="ts">
  import type {
    HTMLAnchorAttributes,
    HTMLButtonAttributes,
  } from "svelte/elements";

  type Variant = "primary" | "ghost" | "outline-dark";

  type BaseProps = {
    variant?: Variant;
  };

  type LinkButtonProps = HTMLAnchorAttributes & {
    href: string;
  };

  type ButtonProps = HTMLButtonAttributes & {
    href?: never;
  };

  type Props = BaseProps & (LinkButtonProps | ButtonProps);

  const baseClasses =
    "flex gap-2 justify-center items-center rounded-sm px-5 py-2 border transition-[background,_filter] text-center";

  const variantClasses: Record<Variant, string> = {
    primary:
      "bg-primary text-text-dark border-border font-medium hover:not-disabled:brightness-80 disabled:text-text-dark/50",
    ghost:
      "bg-primary/10 text-text-light border-primary/15 hover:bg-primary/15",
    "outline-dark":
      "border-border font-medium hover:bg-text-dark hover:text-text-light hover:border-text-dark",
  };

  let { variant = "primary", children, ...rest }: Props = $props();
</script>

{#if rest.href !== undefined}
  <a
    {...rest}
    href={rest.href}
    class={[baseClasses, variantClasses[variant], rest.class]}
    >{@render children?.()}</a
  >
{:else}
  <button {...rest} class={[baseClasses, variantClasses[variant], rest.class]}
    >{@render children?.()}</button
  >
{/if}

// frontend/src/lib/components/button.tsx
import { forwardRef, type ButtonHTMLAttributes } from "react";
import { Link, type LinkOptions } from "@tanstack/react-router"
import { cn } from "../class";

type Variant = "primary" | "secondary";

type BaseProps = Omit<ButtonHTMLAttributes<HTMLButtonElement>, "type"> & {
	variant?: Variant;
};

type ButtonProps = BaseProps & ButtonHTMLAttributes<HTMLButtonElement>

type LinkButtonProps = BaseProps
	& ({
		to: LinkOptions["to"]
		href?: never
	} | {
		to?: never
		href: string;
	})

const baseClasses =
	"flex gap-2 justify-center items-center w-fit px-8 py-2 text-center rounded-sm border border-transparent transition-colors";

const variantClasses = new Map<Variant, string>([
	[
		"primary",
		"bg-background-200 text-text-dark font-medium border-2 border-border hover:bg-background-300",
	],
	[
		"secondary",
		"bg-background-100/10 text-text-light border-background-100/25 hover:bg-background-100/25",
	],
]);



export const Button = forwardRef<HTMLButtonElement, ButtonProps>(({ variant = "primary", ...rest }, ref) => (
	<button
		ref={ref}
		{...rest}
		className={cn(baseClasses, variant && variantClasses.get(variant), rest.className)}
	/>
))

export const LinkButton = ({ to, href, variant = "primary", children, ...rest }: LinkButtonProps) => (
	to
		? <Link to={to} className={cn(baseClasses, variantClasses.get(variant), rest.className)}>{children}</Link>
		: <a href={href} className={cn(baseClasses, variantClasses.get(variant), rest.className)}>{children}</a>
)
