// frontend/src/lib/components/EventEntry.svelte
<script lang="ts">
  import type { Attachment } from "svelte/attachments";

  type Props = {
    title: string;
    src: string;
    description: string;
  };

  let { title, src, description }: Props = $props();

  let isVisible = $state(false);

  const handleVisible: IntersectionObserverCallback = (entries) => {
    entries.map((entry) => {
      isVisible = entry.isIntersecting;
    });
  };

  const observer: Attachment = (element) => {
    const observer = new IntersectionObserver(handleVisible, {
      threshold: 1.0,
      rootMargin: "32px 0px 0px 0px",
    });

    observer.observe(element);
  };
</script>

<div
  class="group relative aspect-3/4 overflow-hidden rounded-sm"
  {@attach observer}
>
  <img
    {src}
    alt={title}
    class="h-full w-full scale-105 transition-[scale] duration-500 group-hover:scale-100"
  />
  <div
    class={[
      "absolute bottom-0 h-2/3 w-full bg-linear-to-t from-[black] opacity-100 transition-opacity duration-500 sm:opacity-50",
      "group-hover:opacity-100",
      isVisible && "sm:opacity-100",
    ]}
  ></div>

  <div class="absolute bottom-0 w-full">
    <div
      class={[
        "absolute -translate-y-full p-5 transition-transform",
        "md:-translate-y-20",
        "md:group-hover:-translate-y-full",
        isVisible && "md:-translate-y-full",
      ]}
    >
      <h2 class="mb-2 font-serif text-2xl font-bold text-text-light">
        {title}
      </h2>
      <p
        class={[
          "text-text-light-muted opacity-0 transition-opacity",
          "md:group-hover:opacity-100",
          isVisible && "opacity-100",
        ]}
      >
        {description}
      </p>
    </div>
  </div>
</div>

// frontend/src/lib/components/event-entry.tsx
import { useEffect, useRef, useState } from "react";
import { cn } from "../class";

type Props = {
	title: string;
	description: string;
	imgSrc: string;
};

const EventEntry = ({ title, description, imgSrc }: Props) => {
	const element = useRef<HTMLDivElement>(null)

	let [isVisible, setIsVisible] = useState(false);

	const handleVisible: IntersectionObserverCallback = (entries, _) => {
		entries.map(({ isIntersecting }) => (
			setIsVisible(isIntersecting)
		));
	};

	useEffect(() => {
		if (!element.current) return
		const observer = new IntersectionObserver(handleVisible, {
			threshold: 1.0,
			rootMargin: "64px 0px -96px 0px",
		});

		observer.observe(element.current);
	}, [element, element.current]);

	return (
		<div
			ref={element}
			className={cn("relative w-full group rounded-md overflow-hidden h-64 md:h-full", isVisible && "is-visible")}
		>
			<img
				src={imgSrc}
				alt={title}
				className="h-full w-full object-cover scale-105 transition-[scale] duration-800 group-hover:scale-100"
			/>
			<div
				className="absolute bottom-0 right-0 w-full h-48 bg-gradient-to-t from-[black] transition-[height]"
			></div>

			<div className="absolute w-full bottom-0">
				<div
					className="absolute -translate-y-full md:-translate-y-20 p-6 transition-transform md:group-hover:-translate-y-full group-[.is-visible]:-translate-y-full"
				>
					<h3 className="font-heading font-bold text-3xl text-text-light mb-4">
						{title}
					</h3>
					<p
						className="text-text-light/80 transition-opacity delay-100 duration-500 md:opacity-0 group-hover:opacity-100 group-[.is-visible]:opacity-100"
					>
						{description}
					</p>
				</div>
			</div>
		</div>
	)
}

export default EventEntry
