// frontend/src/lib/components/input.tsx
import { forwardRef, type InputHTMLAttributes } from "react";
import { cn } from "../class";

const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>((props, ref) => (
	<input
		{...props}
		ref={ref}
		className={cn(
			"bg-background-200 border border-border rounded-sm px-4 py-2",
			props.className
		)} />
))

export default Input

// frontend/src/lib/components/Input.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from "svelte/elements";

  type Props = HTMLInputAttributes & {
    element?: HTMLInputElement;
  };

  let { element = $bindable(), ...rest }: Props = $props();
</script>

<input
  {...rest}
  bind:this={element}
  class={["rounded-sm border border-border px-4 py-2", rest.class]}
/>
