// frontend/src/lib/features/employees/components/EmployeeForm.svelte
<script lang="ts">
  import type { ChangeEventHandler } from "svelte/elements";
  import { type Employee } from "../employee";
  import Input from "$lib/components/Input.svelte";
  import Button from "$lib/components/Button.svelte";
  import AvatarSelector from "$lib/components/AvatarSelector.svelte";
  import FormField from "$lib/components/FormField.svelte";
  import type { createEmployee, updateEmployee } from "../employees.remote";
  import ErrorList from "$lib/components/ErrorList.svelte";

  type CreateProps = {
    variant: "create";
    form: typeof createEmployee;
  };

  type UpdateProps = {
    variant: "update";
    form: typeof updateEmployee;
    employee: Employee;
  };

  type Props = CreateProps | UpdateProps;

  let { ...rest }: Props = $props();

  const { name, role, src } = $derived(rest.form.fields);

  const handleChange: ChangeEventHandler<HTMLInputElement> = (e) => {
    const file = e.currentTarget.files?.item(0);
    if (!file) return;
  };

  $effect(() => {
    if (rest.variant === "create") return;
    rest.form.fields.set({
      ...rest.employee,
      employeeId: rest.employee.id,
      src: undefined,
    });
  });
</script>

<form
  {...rest.form}
  enctype="multipart/form-data"
  class="flex w-full max-w-sm flex-col gap-6"
>
  {#if rest.variant === "update"}
    <input {...rest.form.fields.employeeId.as("hidden", rest.employee.id)} />
  {/if}

  <FormField errors={src.issues()?.map((i) => i.message)}>
    <AvatarSelector
      {...src.as("file")}
      src={rest.variant === "update" ? rest.employee.src : undefined}
      onchange={handleChange}
    />
  </FormField>

  <fieldset class="flex flex-col gap-2">
    <FormField errors={name.issues()?.map((i) => i.message)}>
      <Input {...name.as("text")} placeholder="Navn" />
    </FormField>
    <FormField errors={role.issues()?.map((i) => i.message)}>
      <Input {...role.as("text")} placeholder="Rolle" />
    </FormField>
  </fieldset>

  <ErrorList errors={rest.form.fields.issues()?.map((i) => i.message)} />

  <Button>
    <span class="icon-[lucide--upload]"></span>

    {#if rest.variant === "update"}
      Opdatér
    {:else}
      Tilføj
    {/if}
  </Button>
</form>

// frontend/src/features/employees/components/employee-form.tsx
import { Controller, useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { employeeForm, type Employee } from "../employee"
import type z from "zod"
import Input from "../../../lib/components/input"
import AvatarSelector from "../../../lib/components/avatar-selector"
import { Button } from "../../../lib/components/button"
import ErroneousField from "../../../lib/components/erroneous-field"

type Props = {
	employee?: Employee
	onSubmit: (form: z.infer<typeof employeeForm>) => void;
}

const EmployeeForm = ({ employee, onSubmit }: Props) => {
	const { control, formState: { errors }, register, handleSubmit } = useForm({
		defaultValues: employee ? { ...employee } : undefined,
		resolver: zodResolver(employeeForm)
	})

	return (
		<form className="w-full flex flex-col items-center gap-8" onSubmit={handleSubmit(onSubmit)}>
			<ErroneousField error={errors.image?.message}>
				<Controller
					control={control}
					name="image"
					render={({ field }) => (
						<AvatarSelector
							onChange={field.onChange}
							buttonText={field.value ? "Ændr..." : "Vælg..."}
							src={field.value ? URL.createObjectURL(field.value) : undefined}
						/>
					)}
				/>
			</ErroneousField>

			<fieldset className="flex flex-col gap-2">
				<ErroneousField error={errors.name?.message}>
					<Input placeholder="Navn" {...register("name")} />
				</ErroneousField>

				<ErroneousField error={errors.role?.message}>
					<Input placeholder="Rolle" {...register("role")} />
				</ErroneousField>
			</fieldset>

			<Button className="w-full">{employee ? "Redigér" : "Tilføj"}</Button>
		</form >
	)
}

export default EmployeeForm
