// frontend/src/lib/components/navbar/navbar.tsx
import { Link } from "@tanstack/react-router"
import { LuMenu } from "react-icons/lu"
import Logo from "../logo";
import type { NavEntry } from "./entry";
import Entry from "./entry";
import { cn } from "../../class";

type Props = {
	entries: NavEntry[]
	navMenuOpen: boolean;
	onToggleNavMenu: () => void;
}

const Navbar = ({ entries, navMenuOpen, onToggleNavMenu }: Props) => {
	return (
		<nav
			className="z-20 bg-background-200 fixed w-full px-responsive flex justify-between items-center bg-background border-b border-border"
		>
			<Link to="/" className="py-4">
				<Logo className="fill-text" />
			</Link>
			<ul className="hidden sm:flex">
				{entries.map(({ to, title }) => <Entry to={to} title={title} />)}
			</ul>
			<button
				className={cn("sm:hidden transition-[rotate]", navMenuOpen && "-rotate-90")}
				onClick={onToggleNavMenu}
			>
				<LuMenu />
			</button>
		</nav>
	)
}


export default Navbar

// src/lib/components/Navbar.svelte
<script lang="ts">
  import Logo from "./Logo.svelte";
  import { page } from "$app/state";
  import { Menu } from "@lucide/svelte";

  type Props = {
    navMenuOpen: boolean;
    onOpenNavMenu: () => void;
  };

  let { navMenuOpen, onOpenNavMenu }: Props = $props();
</script>

<nav
  class="bg-background-200 z-50 fixed w-full px-responsive flex justify-between items-center bg-background border-b border-border"
>
  <a href="/" class="py-4">
    <Logo class="fill-text" />
  </a>
  <ul class="hidden sm:flex">
    {@render entry("/menu", "Menu")}
    {@render entry("/om-os", "Om os")}
    {@render entry("/kontakt", "Kontakt")}
  </ul>
  <button
    class:-rotate-90={navMenuOpen}
    class="sm:hidden transition-[rotate]"
    onclick={(e) => {
      e.stopPropagation();
      onOpenNavMenu();
    }}
  >
    <Menu />
  </button>
</nav>

{#snippet entry(pathname: string, title: string)}
  <li class="group" class:active={page.url.pathname.includes(pathname)}>
    <a
      {title}
      class="inline-block text-center entry px-4 font-bold-no-shift py-6 underline-offset-4 decoration-2 group-hover:underline group-[.active]:font-bold group-[.active]:underline"
      href={pathname}>{title}</a
    >
  </li>
{/snippet}
