// frontend/src/routes/auth/login.tsx
import { createFileRoute } from '@tanstack/react-router'
import { LinkButton } from '../../lib/components/button'
import { providerData, providers } from '../../features/auth/auth'
import { env } from '../../env'

export const Route = createFileRoute('/auth/login')({
	component: RouteComponent,
})

function RouteComponent() {
	return (
		<main className="min-h-svh py-32 px-responsive flex justify-center items-center">
			<div>
				<h1 className="text-2xl font-bold font-serif mb-4">Log ind</h1>
				<div className="flex flex-col gap-2">
					{providers.map(provider => {
						const { name, Icon } = providerData(provider)
						const url = new URL(`${env.VITE_BACKEND_URL}/auth/login/${provider}`)

						url.searchParams.set("success_redirect", `${window.location.origin}/admin`)

						return (
							<LinkButton href={url.toString()} className="w-full">
								<Icon />
								Fortsæt med {name}
							</LinkButton>
						)
					})}
				</div>
			</div>
		</main>
	)
}

// src/routes/(app)/auth/login/+page.svelte
<script lang="ts">
  import Button from "$lib/components/Button.svelte";
  import ErrorList from "$lib/components/ErrorList.svelte";
  import FormField from "$lib/components/FormField.svelte";
  import Input from "$lib/components/Input.svelte";
  import type { PageProps } from "./$types";

  let { form }: PageProps = $props();
</script>

<main class="mx-responsive flex min-h-svh items-center justify-center py-32">
  <form method="POST" class="flex flex-col gap-6">
    <h1 class="font-serif text-3xl font-bold">Log ind</h1>

    <fieldset class="flex flex-col gap-2">
      <FormField errors={form?.properties?.email?.errors}>
        <Input type="email" placeholder="Email" name="email" />
      </FormField>
      <FormField errors={form?.properties?.password?.errors}>
        <Input type="password" placeholder="Adgangskode" name="password" />
      </FormField>
      <a href="/auth/reset-password" class="text-right text-sm hover:underline">
        Glemt din adgangskode?
      </a>
    </fieldset>

    <ErrorList errors={form?.errors} />
    <Button type="submit">Log ind</Button>
  </form>
</main>
